"""add password hash to users

Revision ID: c1e44e7e59aa
Revises: 6cb8a4909e5d
Create Date: 2026-08-19 13:43:24.977127

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c1e44e7e59aa'
down_revision: str | None = '6cb8a4909e5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
